#!/usr/bin/env python3
"""
run_sim.py — Compile and simulate Verilog designs using ModelSim CLI.

Usage:
    python run_sim.py --src src/module.v --tb sim/tb_module.v --top tb_module
    python run_sim.py --src src/a.v src/b.v --tb sim/tb_top.v --top tb_top --work my_lib
"""

import argparse
import json
import os
import subprocess
import sys
from datetime import datetime
from pathlib import Path


def run_cmd(cmd: list[str], cwd: str | None = None) -> subprocess.CompletedProcess:
    """Run a command, print it, and return the result."""
    print(f"[run_sim] > {' '.join(cmd)}")
    result = subprocess.run(
        cmd,
        cwd=cwd,
        capture_output=True,
        text=True,
        timeout=300,  # 5-minute hard timeout
    )
    return result


def compile_sources(
    sources: list[str],
    work_lib: str = "work",
    cwd: str | None = None,
) -> bool:
    """Compile Verilog sources with vlog. Returns True on success."""
    # Create the work library if it doesn't exist
    lib_path = Path(cwd or ".") / work_lib
    if not lib_path.exists():
        result = run_cmd(["vlib", work_lib], cwd=cwd)
        if result.returncode != 0:
            print(f"[run_sim] ERROR: vlib failed:\n{result.stderr}", file=sys.stderr)
            return False

    # Compile all source files
    cmd = ["vlog", "-work", work_lib] + sources
    result = run_cmd(cmd, cwd=cwd)

    if result.stdout:
        print(result.stdout)
    if result.stderr:
        print(result.stderr, file=sys.stderr)

    if result.returncode != 0:
        print("[run_sim] ERROR: Compilation failed.", file=sys.stderr)
        return False

    print("[run_sim] Compilation succeeded.")
    return True


def simulate(
    top_module: str,
    work_lib: str = "work",
    cwd: str | None = None,
    log_file: str | None = None,
) -> str:
    """Run simulation in CLI mode. Returns the transcript text."""
    do_cmds = "run -all; quit"
    cmd = [
        "vsim",
        "-c",             # CLI (headless) mode
        "-do", do_cmds,
        f"{work_lib}.{top_module}",
    ]

    if log_file:
        cmd.extend(["-l", log_file])

    result = run_cmd(cmd, cwd=cwd)

    transcript = result.stdout + "\n" + result.stderr

    if log_file:
        log_path = Path(cwd or ".") / log_file
        try:
            log_path.write_text(transcript, encoding="utf-8")
            print(f"[run_sim] Transcript saved to {log_file}")
        except OSError as e:
            print(f"[run_sim] WARNING: Could not write log file: {e}", file=sys.stderr)

    return transcript


def write_sim_result(
    status: str,
    summary: str,
    log_file: str | None = None,
    top_module: str = "",
    cwd: str | None = None,
) -> None:
    """Write sim/sim_result.json as a handoff artifact for quartus-agent."""
    base = Path(cwd or ".")
    sim_dir = base / "sim"
    sim_dir.mkdir(parents=True, exist_ok=True)

    # Try to find the VCD file generated by the testbench
    vcd_file = None
    for vcd in sim_dir.glob("*.vcd"):
        vcd_file = str(vcd.relative_to(base))
        break
    # Also check current directory
    if vcd_file is None:
        for vcd in base.glob("*.vcd"):
            vcd_file = str(vcd.relative_to(base))
            break

    # Check for waveform images
    waveform_image = None
    waveforms_dir = sim_dir / "waveforms"
    if waveforms_dir.exists():
        for img in waveforms_dir.glob("*.png"):
            waveform_image = str(img.relative_to(base))
            break

    result = {
        "status": status,
        "timestamp": datetime.now().isoformat(),
        "log_file": log_file,
        "vcd_file": vcd_file,
        "waveform_image": waveform_image,
        "summary": summary,
    }

    result_path = sim_dir / "sim_result.json"
    result_path.write_text(json.dumps(result, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"[run_sim] Handoff file written: {result_path}")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Compile and simulate Verilog designs with ModelSim CLI."
    )
    parser.add_argument(
        "--src",
        nargs="+",
        required=True,
        help="RTL source file(s) to compile.",
    )
    parser.add_argument(
        "--tb",
        nargs="+",
        required=True,
        help="Testbench file(s) to compile.",
    )
    parser.add_argument(
        "--top",
        required=True,
        help="Top-level testbench module name for simulation.",
    )
    parser.add_argument(
        "--work",
        default="work",
        help="Work library name (default: work).",
    )
    parser.add_argument(
        "--log",
        default="sim_output.log",
        help="Output log file name (default: sim_output.log).",
    )
    parser.add_argument(
        "--cwd",
        default=None,
        help="Working directory for compilation and simulation.",
    )

    args = parser.parse_args()

    all_files = args.src + args.tb

    # Validate that files exist
    base = Path(args.cwd) if args.cwd else Path(".")
    for f in all_files:
        if not (base / f).exists():
            print(f"[run_sim] ERROR: File not found: {f}", file=sys.stderr)
            sys.exit(1)

    # Step 1: Compile
    if not compile_sources(all_files, work_lib=args.work, cwd=args.cwd):
        write_sim_result(
            status="FAIL",
            summary="Compilation failed. Check vlog errors.",
            log_file=args.log,
            top_module=args.top,
            cwd=args.cwd,
        )
        sys.exit(1)

    # Step 2: Simulate
    transcript = simulate(
        top_module=args.top,
        work_lib=args.work,
        cwd=args.cwd,
        log_file=args.log,
    )

    # Step 3: Analyze & write handoff
    lines = transcript.strip().splitlines()
    error_lines = [l for l in lines if "error" in l.lower() or "fatal" in l.lower()]
    if error_lines:
        print("\n[run_sim] === ERRORS DETECTED ===")
        for l in error_lines:
            print(f"  {l}")
        write_sim_result(
            status="FAIL",
            summary=f"{len(error_lines)} error(s) detected during simulation.",
            log_file=args.log,
            top_module=args.top,
            cwd=args.cwd,
        )
        sys.exit(1)
    else:
        print("\n[run_sim] Simulation completed. Check log for details.")
        write_sim_result(
            status="PASS",
            summary="Simulation completed successfully. No errors detected.",
            log_file=args.log,
            top_module=args.top,
            cwd=args.cwd,
        )


if __name__ == "__main__":
    main()
